#The URL the site will be built for
base_url = "https://sasza.ar"
title = "sasza.ar"
description = "sasha's personal website"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Theme
theme = "terminimal"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

external_links_target_blank = true

[extra]
# Put all your custom variables here
author = "sasha berkowsky"

# terminimal config
logo_text = "sasza.ar"
accent_color = "orange"
background_color = "orange"
menu_items = [
    {name = "about", url = "$BASE_URL/about"},
    {name = "background", url = "$BASE_URL/background"},
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "tools", url = "$BASE_URL/tools"},
    {name = "github", url = "https://github.com/sashaberkowsky", newtab = true},
    {name = "linkedin", url = "https://linkedin.com/in/sasha-berkowsky", newtab = true},
    {name = "resume", url = "$BASE_URL/docs/resume.pdf", newtab = true},
]
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
page_titles = "combined"
favicon = "/img/favicon.ico"
favicon_mimetype = "image/x-ico"
